#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

DAY=${1}

if [[ -z $DAY ]]; then
    read -r -p 'Which day? ' DAY
fi

DEST_DIR="${SCRIPT_DIR}/Sources/day${DAY}"

if [[ -d "$DEST_DIR" ]]; then
    echo "error: ${DEST_DIR} already exists"
    exit 1
fi

cp -r "${SCRIPT_DIR}/Sources/.template" "${DEST_DIR}"

sed -i '' 's/<#day#>/Day'"${DAY}"'/' "${DEST_DIR}/day.swift"
mv "${DEST_DIR}/day.swift" "${DEST_DIR}/day${DAY}.swift"

echo "Add this to Package.swift"

cat <<EOF

        .executableTarget(
            name: "day3",
            dependencies: [
                "Util",
                .product(name: "ArgumentParser", package: "swift-argument-parser")
            ],
            exclude: excludes),
EOF